// Ubah request + assertion menjadi teks test case (Markdown) yang bisa
// dipakai untuk issue tracker maupun export file.

import { describeAssertion } from "../assert";
import type { HttpRequest } from "../types";
import type { IssuePayload } from "./types";

function requestLine(req: HttpRequest): string {
  return `${req.method} ${req.url || "(no url)"}`;
}

/** Ringkas satu request menjadi judul issue. */
export function issueTitle(req: HttpRequest): string {
  const name = req.name?.trim();
  return name ? `[API Test] ${name}` : `[API Test] ${requestLine(req)}`;
}

/** Bangun body Markdown untuk satu test case. */
export function testCaseMarkdown(req: HttpRequest): string {
  const lines: string[] = [];
  lines.push(`**Request**`);
  lines.push("");
  lines.push("```");
  lines.push(requestLine(req));
  for (const h of req.headers.filter((h) => h.enabled && h.key)) {
    lines.push(`${h.key}: ${h.value}`);
  }
  if (req.body.kind === "json" || req.body.kind === "text") {
    if (req.body.content.trim()) {
      lines.push("");
      lines.push(req.body.content.trim());
    }
  }
  lines.push("```");
  lines.push("");

  const asserts = req.assertions.filter((a) => a.enabled);
  lines.push(`**Expected (${asserts.length} assertion${asserts.length === 1 ? "" : "s"})**`);
  lines.push("");
  if (asserts.length === 0) {
    lines.push("- _(no assertions yet)_");
  } else {
    for (const a of asserts) lines.push(`- [ ] ${describeAssertion(a)}`);
  }
  lines.push("");
  lines.push(`_Generated by Proxius._`);
  return lines.join("\n");
}

/** Payload netral-provider untuk satu request. */
export function toIssuePayload(req: HttpRequest): IssuePayload {
  return {
    title: issueTitle(req),
    markdown: testCaseMarkdown(req),
    labels: ["proxius", "api-test"],
  };
}

/** Export beberapa test case sebagai satu dokumen Markdown. */
export function exportMarkdown(requests: HttpRequest[], heading = "Test Cases"): string {
  const out: string[] = [`# ${heading}`, ""];
  for (const req of requests) {
    out.push(`## ${issueTitle(req)}`, "", testCaseMarkdown(req), "");
  }
  return out.join("\n");
}
