[package]
name = "proxius-engine"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
proxius-core = { path = "../core" }
reqwest.workspace = true
tokio.workspace = true
serde.workspace = true
async-trait.workspace = true
anyhow.workspace = true
futures.workspace = true
